name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
permissions:
  checks: write
  statuses: write
  contents: read
  pull-requests: write
jobs:
  Test_iOS:
    if: github.event.pull_request.draft == false
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Package
        id: build
        run: |
          xcrun xcodebuild clean build-for-testing  \
            -scheme Injector \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            -quiet \
            -skipPackagePluginValidation
      - name: Test
        id: test
        if: steps.build.outcome == 'success'
        run: |
          xcrun xcodebuild test-without-building \
            -scheme Injector \
            -resultBundlePath iOSResults \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            -enableCodeCoverage YES \
            -quiet \
            -retry-tests-on-failure \
            -test-iterations 3 \
            -skipPackagePluginValidation
      - name: Generate Reports
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: iOSResults.xcresult
          title: iOS Test Results
          show-passed-tests: false
        if: success() || failure()
  Test_tvOS:
    if: github.event.pull_request.draft == false
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Package
        id: build
        run: |
          xcrun xcodebuild clean build-for-testing \
            -scheme Injector \
            -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=17.4' \
            -quiet \
            -skipPackagePluginValidation
      - name: Test
        id: test
        if: steps.build.outcome == 'success'
        run: |
          xcrun xcodebuild test-without-building \
            -scheme Injector \
            -resultBundlePath tvOSResults \
            -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=17.4' \
            -enableCodeCoverage YES \
            -quiet \
            -retry-tests-on-failure \
            -test-iterations 3 \
            -skipPackagePluginValidation
      - name: Generate Reports
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: tvOSResults.xcresult
          title: tvOS Test Results
          show-passed-tests: false
        if: success() || failure()
  Test_visionOS:
    if: github.event.pull_request.draft == false
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Package
        id: build
        run: |
          xcrun xcodebuild clean build-for-testing \
            -scheme Injector \
            -destination 'platform=visionOS Simulator,name=Apple Vision Pro ,OS=1.1' \
            -quiet \
            -skipPackagePluginValidation
      - name: Test
        id: test
        if: steps.build.outcome == 'success'
        run: |
          xcrun xcodebuild test-without-building \
            -scheme Injector \
            -resultBundlePath visionOSResults \
            -destination 'platform=visionOS Simulator,name=Apple Vision Pro ,OS=1.1' \
            -enableCodeCoverage YES \
            -quiet \
            -retry-tests-on-failure \
            -test-iterations 3 \
            -skipPackagePluginValidation
      - name: Generate Reports
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: visionOSResults.xcresult
          title: visionOS Test Results
          show-passed-tests: false
        if: success() || failure()
