name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
permissions:
  checks: write
  statuses: write
  contents: read
  pull-requests: write
jobs:
  Build_And_Test:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        run: [{scheme: Injector, platform: 'iOS', device: 'iPhone 16', os_version: '18.2'},
              {scheme: Injector, platform: 'tvOS', device: 'Apple TV 4K (3rd generation)', os_version: '18.2'},
              {scheme: Injector, platform: 'visionOS', device: 'Apple Vision Pro', os_version: '2.2'}]
    env:
      scheme: ${{ matrix.run.scheme }}
      platform: ${{ matrix.run.platform }}
      device: ${{ matrix.run.device }}
      os_version: ${{ matrix.run.os_version }}
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Package
        id: build
        run: |
          xcrun xcodebuild clean build-for-testing  \
            -scheme ${scheme} \
            -destination "platform=${platform} Simulator,name=${device},OS=${os_version}" \
            -quiet \
            -skipPackagePluginValidation
      - name: Test
        id: test
        if: steps.build.outcome == 'success'
        run: |
          xcrun xcodebuild test-without-building \
            -scheme ${scheme} \
            -resultBundlePath ${platform}_Results.xcresult \
            -destination "platform=${platform} Simulator,name=${device},OS=${os_version}" \
            -enableCodeCoverage YES \
            -quiet \
            -retry-tests-on-failure \
            -test-iterations 3 \
            -skipPackagePluginValidation
      - name: Generate Reports
        uses: conradev/xcresulttool@025dba02b4af8bb6618db636b7447227ee20f62b
        continue-on-error: true
        with:
          path: ${{ matrix.run.platform }}_Results.xcresult
          title: ${{ matrix.run.platform }} Test Results
          show-passed-tests: false
        if: success() || failure()
