name: Warning Analyzer

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, converted_to_draft]
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  buildBase:
    runs-on: macos-latest #macos-14-xlarge
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.base_ref }}
        fetch-depth: 1
    - name: Set up Homebrew
      run: brew update
    - name: Install XCLogParser
      run: brew install xclogparser
    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.3.app
    - name: Build and analyze ${{ github.base_ref }} branch
      run: |
        xcodebuild clean build \
        -scheme Injector \
        -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
        -derivedDataPath build \
        -resultBundlePath build/Result
    - name: Parse Build Log
      run: xclogparser parse --derived_data ./build --project Injector --reporter issues --output issues.json
    - uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        retention-days: 1
        name: base_issues
        path: issues.json
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Homebrew
      run: brew update
    - name: Install XCLogParser
      run: brew install xclogparser
    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.3.app
    - name: Build and analyze ${{ github.head_ref }} branch
      run: |
        xcodebuild clean build \
        -scheme Injector \
        -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
        -derivedDataPath build \
        -resultBundlePath build/Result
    - name: Parse Build Log
      run: xclogparser parse --derived_data ./build --project Injector --reporter issues --output issues.json
    - uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        retention-days: 1
        name: new_issues
        path: issues.json
  compare:
    runs-on: ubuntu-latest
    needs: [buildBase, build]
    steps:
      - uses: actions/download-artifact@v4
      - name: Compare ${{ github.head_ref }} issues with ${{ github.base_ref }} issues
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const fs = require('fs');
              const newIssues = JSON.parse(fs.readFileSync('./new_issues/issues.json'))
              const baseIssues = JSON.parse(fs.readFileSync('./base_issues/issues.json'))
              console.dir(newIssues)
              console.dir(baseIssues)
              if (newIssues.errors.length > baseIssues.errors.length) {
                core.error("New Errors: ${newIssues.errors.length}")
                core.setFailed("New Errors: ${newIssues.errors.length}")
              }

              if (newIssues.warnings.length > baseIssues.warning.length) {
                core.error("New Warnings: ${newIssues.warnings.length}")
                core.setFailed("New Warnings: ${newIssues.warnings.length}")
              }

            } catch(err) {
              core.error("Comparison failed")
              core.setFailed(err)
            }
